image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  #- ps: Vsix-TokenReplacement ResPsuedoLoc\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore .\src\ResPsuedoLoc\ResPsuedoLoc.sln -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m .\src\ResPsuedoLoc\ResPsuedoLoc.sln

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery

skip_commits:
  files:
    - assets/*
    - docs/*
    - '**/*.md'
    