// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResPsuedoLoc
{
    internal sealed partial class Vsix
    {
        public const string Id = "ResPsuedoLoc.fb9c5e68-fb3b-44f4-9412-717109dc3ba9";
        public const string Name = "Resource Pseudo Localizer";
        public const string Description = @"Quickly and easily convert the values in RESX and RESW files to their pseudo localized versions to help detect any text that doesn't come from a resource file.";
        public const string Language = "en-US";
        public const string Version = "3.5.5";
        public const string Author = "Matt Lacey";
        public const string Tags = "RESX, RESW, resources, localization, i18n, testing";
    }
}
